name: release
on:
  push:
    tags:
    - 'v200.[0-9]+.[0-9]+'
    - 'v200.[0-9]+.[0-9]+-beta.[0-9]+'

permissions:
  contents: write

jobs:
  checksum_file:
    runs-on: ubuntu-22.04
    environment: release-updates-static-web-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Commit post release updates changes
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          echo "$(date)" >> file.txt

          git add file.txt
          git commit --verbose -m "docs: ${{ env.SERVER_VERSION }} [skip ci]"
          git checkout -b release-docs-${{ env.SERVER_VERSION }}
          git push --verbose

      - name: Create merge request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Documentation for release ${{ env.SERVER_VERSION }} [skip ci]" \
            --body "This PR updates the corresponding documentation pages for the current release \`${{ env.SERVER_VERSION }}\`." \
            --base "master" \
            --head "release-docs-${{ env.SERVER_VERSION }}" \
            --label "v2" --label "enhancement" --label "documentation" \
            --draft
